name: notecast
channels:
  - defaults
  - conda-forge
dependencies:
  - torchvision
  - pytorch
  - torchaudio
  - transformers
  - accelerate
  - ffmpeg
  - pyinstaller
  - customtkinter
  - isort
  - mypy
  - black